name: CI

on:
  push:
    branches: 'main'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v5
      - uses: oven-sh/setup-bun@v2

      - run: just ci
