name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v5
      - uses: oven-sh/setup-bun@v2

      - env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: just ci-pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
